# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod_name = Dynamic Surroundings
mod_description = Alters the fabric of Minecraft experience by weaving a tapestry of sound and visual effects
mod_version = 0.5.0
mod_author = OreCruncher
mod_license = MIT
mod_issues_url = https://github.com/OreCruncher/DynamicSurroundingsFabric/issues
mod_homepage_url = https://github.com/OreCruncher/DynamicSurroundingsFabric
maven_group = org.orecruncher
archives_name = dynamicsurroundings
enabled_platforms = fabric,neoforge

# Minecraft properties
minecraft_version = 26.2

# Dependencies
architectury_api_version = 21.1.10
fabric_loader_version = 0.19.5
fabric_api_version = 0.161.0+26.2
neoforge_version = 26.2.0.82

# Mods
glitchcore_version = 26.2.0.0.0
serene_seasons_version = 26.1.2.0.6
bop_version = 26.2.0.0.24
terrablender_version = 26.2.0.0.2
clothapi_version = 26.2.155
yacl_version = 3.9.7+26.2
modmenu_version = 20.0.3