modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "${mod_issues_url}"
displayURL="${mod_homepage_url}"
license = "${mod_license}"

[[mods]]
modId = "dsurround"
version = "${version}"
displayName = "${mod_name}"
authors = "${mod_author}"
description = '''
${mod_description}
'''
logoFile = "assets/dsurround/icon.png"

[[dependencies.dsurround]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.dsurround]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.dsurround]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "dsurround.mixins.json"
