modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/OreCruncher/DynamicSurroundingsFabric/issues"
license = "MIT"

[[mods]]
modId = "dsurround"
version = "${version}"
displayName = "Dynamic Surroundings"
authors = "OreCruncher"
description = '''
Alters the fabric of Minecraft experience by weaving a tapestry of sound and visual effects
'''
logoFile = "assets/dsurround/icon.png"

[[dependencies.dsurround]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.dsurround]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.dsurround]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "dsurround.mixins.json"
